#FROM debian:buster-slim
FROM openjdk:17-jdk-slim
WORKDIR /app

COPY build.gradle build.gradle gradlew /app/
COPY src /app/src
COPY gradle /app/gradle
#COPY build/libs/kestler-1.0.jar /app/allane.jar

EXPOSE 8080
RUN ./gradlew bootJar

CMD ["java", "-jar", "/app/build/libs/app-1.0.jar"]